var Semanas = {
    "SEMANA 1": {
        "Titulo": "Tecnologías web y Visual Studio Code",
        "Definiciones": "Definición: La semana se centra en comprender las tecnologías fundamentales utilizadas en el desarrollo web, junto con la introducción al entorno de desarrollo Visual Studio Code. Las tecnologías web pueden incluir conceptos como el funcionamiento de Internet, el modelo cliente-servidor y los protocolos básicos.",
        "Procedimiento": "Durante esta semana, los participantes pueden explorar los conceptos fundamentales de las tecnologías web, comprendiendo cómo los navegadores interactúan con los servidores. Además, se familiarizarán con Visual Studio Code, un entorno de desarrollo integrado (IDE) ampliamente utilizado, aprendiendo a configurarlo y utilizar sus características esenciales.",
        "Resultados": "Al finalizar la semana, los participantes deben tener una comprensión sólida de las tecnologías esenciales que sustentan el desarrollo web y sentirse cómodos trabajando con Visual Studio Code para la creación y edición de código.",
        "¿Qué aprendió?": "text_text_text111",
        "¿Cómo aprendió?": "text_text_text111",
    },
    "SEMANA 2": {
        "Titulo": "HTML, CSS y librerías (framework) parte 1",
        "Definiciones": "Esta semana se enfoca en dos lenguajes fundamentales del desarrollo web: HTML (Hypertext Markup Language) y CSS (Cascading Style Sheets). Además, se aborda la introducción a librerías o frameworks que facilitan el desarrollo web, como Bootstrap o Tailwind CSS.",
        "Procedimiento": "Los participantes aprenderán a estructurar contenido web utilizando HTML, definiendo la jerarquía y relación entre elementos. Luego, se sumergirán en CSS para dar estilo y diseño a las páginas web. La introducción a librerías o frameworks proporcionará herramientas adicionales para agilizar el desarrollo, permitiendo estilos predefinidos y componentes reutilizables.",
        "Resultados": "Al término de la semana, los participantes deberían ser capaces de construir páginas web simples utilizando HTML y CSS, y comprender el uso básico de librerías o frameworks para mejorar la eficiencia del desarrollo.",
        "¿Qué aprendió?": "text_text_text222",
        "¿Cómo aprendió?": "text_text_text222",
    },
    "SEMANA 3": {
        "Titulo": "HTML, CSS y librerías (framework) parte 2",
        "Definiciones": "Continuando con la semana anterior, se profundiza en el uso avanzado de HTML y CSS, explorando características más complejas y practicando la creación de diseños web más elaborados. Además, se puede introducir el concepto de preprocesadores CSS, como Sass o Less.",
        "Procedimiento": "Los participantes se sumergirán en técnicas avanzadas de HTML y CSS, explorando conceptos como flexbox, diseño de cuadrícula y transiciones. La introducción a preprocesadores CSS les permitirá optimizar y organizar su código de estilo de manera más eficiente.",
        "Resultados": "Al concluir la semana, los participantes deberían estar familiarizados con técnicas avanzadas de maquetación web, y ser capaces de utilizar preprocesadores CSS para mejorar la mantenibilidad y modularidad de su código.",
        "¿Qué aprendió?": "text_text_text333",
        "¿Cómo aprendió?": "text_text_text333",
    },
    "SEMANA 4": {
        "Titulo": "JavaScript",
        "Definiciones": "En esta semana, se aborda el lenguaje de programación JavaScript, esencial para el desarrollo web interactivo. Se exploran conceptos básicos como variables, operadores, estructuras de control, funciones y objetos.",
        "Procedimiento": "Los participantes se sumergen en la programación con JavaScript, aprendiendo a manipular el DOM (Document Object Model) para interactuar dinámicamente con las páginas web. Se abordan también conceptos esenciales como eventos, AJAX y manipulación de datos.",
        "Resultados": "Al finalizar la semana, los participantes deberían ser capaces de escribir scripts en JavaScript para crear interactividad en sus páginas web, comprendiendo los conceptos básicos y aplicándolos en proyectos simples.",
        "¿Qué aprendió?": "text_text_text444",
        "¿Cómo aprendió?": "text_text_text444",
    },
    "SEMANA 5": {
        "Titulo": "Introducción al desarrollo con React",
        "Definiciones": "La última semana se centra en React, una biblioteca de JavaScript para construir interfaces de usuario interactivas y reutilizables. Se explora el concepto de componentes y el enfoque de desarrollo basado en la creación de interfaces modulares.",
        "Procedimiento": "La última semana se centra en React, una biblioteca de JavaScript para construir interfaces de usuario interactivas y reutilizables. Se explora el concepto de componentes y el enfoque de desarrollo basado en la creación de interfaces modulares.",
        "Resultados": "Al concluir la semana, los participantes deberían estar familiarizados con el desarrollo de aplicaciones web utilizando React, siendo capaces de construir interfaces modulares y comprender los principios clave de esta tecnología.",
        "¿Qué aprendió?": "text_text_text555",
        "¿Cómo aprendió?": "text_text_text555",
    },
    "SEMANA 6": {
        "Titulo": "text_text_text",
        "Definiciones": "text_text_text",
        "Procedimiento": "text_text_text",
        "Resultados": "text_text_text",
        "¿Qué aprendió?": "text_text_text",
        "¿Cómo aprendió?": "text_text_text",
    },
    "SEMANA 7": {
        "Titulo": "text_text_text",
        "Definiciones": "text_text_text",
        "Procedimiento": "text_text_text",
        "Resultados": "text_text_text",
        "¿Qué aprendió?": "text_text_text",
        "¿Cómo aprendió?": "text_text_text",
    },
    "SEMANA 8": {
        "Titulo": "text_text_text",
        "Definiciones": "text_text_text",
        "Procedimiento": "text_text_text",
        "Resultados": "text_text_text",
        "¿Qué aprendió?": "text_text_text",
        "¿Cómo aprendió?": "text_text_text",
    },
    "SEMANA 9": {
        "Titulo": "text_text_text",
        "Definiciones": "text_text_text",
        "Procedimiento": "text_text_text",
        "Resultados": "text_text_text",
        "¿Qué aprendió?": "text_text_text",
        "¿Cómo aprendió?": "text_text_text",
    },
    "SEMANA 10": {
        "Titulo": "text_text_text",
        "Definiciones": "text_text_text",
        "Procedimiento": "text_text_text",
        "Resultados": "text_text_text",
        "¿Qué aprendió?": "text_text_text",
        "¿Cómo aprendió?": "text_text_text",
    },
    "SEMANA 11": {
        "Titulo": "text_text_text",
        "Definiciones": "text_text_text",
        "Procedimiento": "text_text_text",
        "Resultados": "text_text_text",
        "¿Qué aprendió?": "text_text_text",
        "¿Cómo aprendió?": "text_text_text",
    },
    "SEMANA 12": {
        "Titulo": "text_text_text",
        "Definiciones": "text_text_text",
        "Procedimiento": "text_text_text",
        "Resultados": "text_text_text",
        "¿Qué aprendió?": "text_text_text",
        "¿Cómo aprendió?": "text_text_text",
    },
    "SEMANA 13": {
        "Titulo": "text_text_text",
        "Definiciones": "text_text_text",
        "Procedimiento": "text_text_text",
        "Resultados": "text_text_text",
        "¿Qué aprendió?": "text_text_text",
        "¿Cómo aprendió?": "text_text_text",
    },
    "SEMANA 14": {
        "Titulo": "text_text_text",
        "Definiciones": "text_text_text",
        "Procedimiento": "text_text_text",
        "Resultados": "text_text_text",
        "¿Qué aprendió?": "text_text_text",
        "¿Cómo aprendió?": "text_text_text",
    }
};

export { Semanas };